image: kkarczmarczyk/node-yarn:latest

stages:
  - lint
  - analysis
  - deploy

eslint:
  stage: lint
  cache:
      paths:
        - 'node_modules/'
  before_script:
    - yarn global add eslint eslint-plugin-angular
  script:
    - eslint --init
    - eslint client/app/**/*.js

jsinspect:
  stage: analysis
  cache:
      paths:
        - 'node_modules/'
  before_script:
    - yarn global add jsinspect
  script:
    - jsinspect ./client/app

stylelint:
  stage: lint
  cache:
      paths:
        - 'node_modules/'
  before_script:
    - yarn global add stylint stylint-stylish
  script:
    - cd client/app
    - stylint -r stylint-stylish

firebase:
  stage: deploy
  cache:
      paths:
        - 'node_modules/'
  environment: Production
  before_script:
    - yarn global add firebase-tools
    - yarn install
  script:
    - yarn run build
    - firebase deploy -m 'Deploy to production $CI_BUILD_ID' --non-interactive --token $FIREBASE_DEPLOY_TOKEN --project melon-28470
